version: '2'
services:
  gogs_server:
    image: gogs/gogs:0.10.18
    ports:
      - "3000:3000"
      - "10022:22"
    volumes:
      - gogs_server_data:/data
    networks:
      - gogs_network
    depends_on:
      - gogs_db
  gogs_db:
    image: mysql:5.6
    ports:
       - "3306:3306"
    volumes:
      - gogs_db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=gogs
    networks:
      gogs_network:
        aliases:
          - mysql
volumes:
  gogs_server_data:
    driver: local
  gogs_db_data:
    driver: local
networks:
  gogs_network:
